apiVersion: v1
kind: Pod
metadata:
  name: host-service
  namespace: test
  labels:
    app: host-service
spec:
  containers:
  - name: host-service
    image: nginx:alpine
    ports:
      - containerPort: 80