apiVersion: v1
kind: Service
metadata:
  name: host-service
  namespace: test
spec:
  selector:
    app: host-service
  ports:
    - port: 8080       # Cluster port inside Kubernetes
      targetPort: 80   # NGINX container port
  type: NodePort        # Important — must be NodePort